### ISSUE TITLE
Typo in name

### ISSUE THREAD

**Issue by gianlucamazza** [OpenDataFormats/simplestamp#1]
The original name is opentimestamps from https://opentimestamps.org/

**Comment by davidarvan** [comment]
Thanks! That's actually intentional. This package doesn't include the CLI or any means to timestamp multiple files at once (it doesn't dictate files at all, just a hash). Hence it being singular rather than plural. Would it make sense to add this to the README?

**Comment by gianlucamazza** [comment]
I would probably suggest to rename to something more appropriate, if not possible probably also a disclaimer in the README is a good idea.
When I found this project I was thinking it was the official cli from opentimestamps.. bte I'm implementing your lib into my project to give a try

**Comment by davidarvan** [comment]
👊   Renamed it and scoped it to the organization, to be more clear. Thanks for the feedback!
